export const striveRanks = [
  "Iron",
  "Bronze",
  "Silver",
  "Gold",
  "Platinum",
  "Diamond",
  "Master",
  "Grand Master",
  "Celestial",
  "Vanquisher"
] as const;

export const striveCharacters = [
  "Sol Badguy",
  "Ky Kiske",
  "May",
  "Axl Low",
  "Chipp Zanuff",
  "Potemkin",
  "Faust",
  "Millia Rage",
  "Zato-1",
  "Ramlethal Valentine",
  "Leo Whitefang",
  "Nagoriyuki",
  "Giovanna",
  "Anji Mito",
  "I-No",
  "Goldlewis Dickinson",
  "Jack-O'",
  "Happy Chaos",
  "Baiken",
  "Testament",
  "Bridget",
  "Sin Kiske",
  "Bedman?",
  "Asuka R#",
  "Johnny",
  "Elphelt Valentine",
  "A.B.A",
  "Slayer",
  "Queen Dizzy",
  "Venom",
  "Unika",
  "Lucy",
  "Jam Kuradoberi",
  "Robo-Ky"
] as const;
